/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard/index'
import { Route as DashboardDashboardProfileRouteImport } from './routes/_dashboard/dashboard/profile'
import { Route as AuthAuthVerifyEmailRouteImport } from './routes/_auth/auth/verify-email'
import { Route as AuthAuthRegisterRouteImport } from './routes/_auth/auth/register'
import { Route as AuthAuthLoginRouteImport } from './routes/_auth/auth/login'
import { Route as AuthAuthForgotPasswordRouteImport } from './routes/_auth/auth/forgot-password'
import { Route as AuthAuthResetPasswordResetIdRouteImport } from './routes/_auth/auth/reset-password/$reset-id'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardProfileRoute =
  DashboardDashboardProfileRouteImport.update({
    id: '/dashboard/profile',
    path: '/dashboard/profile',
    getParentRoute: () => DashboardRoute,
  } as any)
const AuthAuthVerifyEmailRoute = AuthAuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthRegisterRoute = AuthAuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthLoginRoute = AuthAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthForgotPasswordRoute = AuthAuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthResetPasswordResetIdRoute =
  AuthAuthResetPasswordResetIdRouteImport.update({
    id: '/auth/reset-password/$reset-id',
    path: '/auth/reset-password/$reset-id',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth/forgot-password': typeof AuthAuthForgotPasswordRoute
  '/auth/login': typeof AuthAuthLoginRoute
  '/auth/register': typeof AuthAuthRegisterRoute
  '/auth/verify-email': typeof AuthAuthVerifyEmailRoute
  '/dashboard/profile': typeof DashboardDashboardProfileRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/auth/reset-password/$reset-id': typeof AuthAuthResetPasswordResetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth/forgot-password': typeof AuthAuthForgotPasswordRoute
  '/auth/login': typeof AuthAuthLoginRoute
  '/auth/register': typeof AuthAuthRegisterRoute
  '/auth/verify-email': typeof AuthAuthVerifyEmailRoute
  '/dashboard/profile': typeof DashboardDashboardProfileRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/auth/reset-password/$reset-id': typeof AuthAuthResetPasswordResetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/admin': typeof AdminRoute
  '/_auth/auth/forgot-password': typeof AuthAuthForgotPasswordRoute
  '/_auth/auth/login': typeof AuthAuthLoginRoute
  '/_auth/auth/register': typeof AuthAuthRegisterRoute
  '/_auth/auth/verify-email': typeof AuthAuthVerifyEmailRoute
  '/_dashboard/dashboard/profile': typeof DashboardDashboardProfileRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_auth/auth/reset-password/$reset-id': typeof AuthAuthResetPasswordResetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-email'
    | '/dashboard/profile'
    | '/dashboard'
    | '/auth/reset-password/$reset-id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-email'
    | '/dashboard/profile'
    | '/dashboard'
    | '/auth/reset-password/$reset-id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dashboard'
    | '/admin'
    | '/_auth/auth/forgot-password'
    | '/_auth/auth/login'
    | '/_auth/auth/register'
    | '/_auth/auth/verify-email'
    | '/_dashboard/dashboard/profile'
    | '/_dashboard/dashboard/'
    | '/_auth/auth/reset-password/$reset-id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  AdminRoute: typeof AdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/profile': {
      id: '/_dashboard/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardDashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/auth/verify-email': {
      id: '/_auth/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthAuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/auth/register': {
      id: '/_auth/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthAuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/auth/login': {
      id: '/_auth/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthAuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/auth/forgot-password': {
      id: '/_auth/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthAuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/auth/reset-password/$reset-id': {
      id: '/_auth/auth/reset-password/$reset-id'
      path: '/auth/reset-password/$reset-id'
      fullPath: '/auth/reset-password/$reset-id'
      preLoaderRoute: typeof AuthAuthResetPasswordResetIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAuthForgotPasswordRoute: typeof AuthAuthForgotPasswordRoute
  AuthAuthLoginRoute: typeof AuthAuthLoginRoute
  AuthAuthRegisterRoute: typeof AuthAuthRegisterRoute
  AuthAuthVerifyEmailRoute: typeof AuthAuthVerifyEmailRoute
  AuthAuthResetPasswordResetIdRoute: typeof AuthAuthResetPasswordResetIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthForgotPasswordRoute: AuthAuthForgotPasswordRoute,
  AuthAuthLoginRoute: AuthAuthLoginRoute,
  AuthAuthRegisterRoute: AuthAuthRegisterRoute,
  AuthAuthVerifyEmailRoute: AuthAuthVerifyEmailRoute,
  AuthAuthResetPasswordResetIdRoute: AuthAuthResetPasswordResetIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardDashboardProfileRoute: typeof DashboardDashboardProfileRoute
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardProfileRoute: DashboardDashboardProfileRoute,
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  AdminRoute: AdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
